name: Transcribe YouTube Video

on:
  workflow_dispatch:
    inputs:
      youtube_url:
        description: 'YouTube Video URL'
        required: true
        type: string

jobs:
  transcribe:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install ffmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: Create cookies.txt from secret
      run: |
        echo "${{ secrets.YOUTUBE_COOKIES }}" > cookies.txt

    - name: Run transcription
      run: |
        python run.py "${{ github.event.inputs.youtube_url }}"


    - name: Upload Whisper output
      uses: actions/upload-artifact@v3
      with:
        name: whisper-output
        path: |
          title.txt
          script.txt
      