name: Transcribe YouTube Video

on:
  workflow_dispatch:
    inputs:
      youtube_url:
        description: 'YouTube Video URL'
        required: true
        type: string

jobs:
  transcribe:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run transcription
      run: |
        python run.py "${{ github.event.inputs.youtube_url }}"

    - name: Upload title
        uses: actions/upload-artifact@8d89c40d9c1c1f203d5bcf274fc02d78ebd3a63a
        with:
        name: title
        path: title.txt
  
    - name: Upload script
        uses: actions/upload-artifact@8d89c40d9c1c1f203d5bcf274fc02d78ebd3a63a
        with:
        name: script
        path: script.txt
  